### ISSUE TITLE
Fails on some zip urls

### ISSUE THREAD

**Issue by quietlyconfident** [fcvarela/pyremotezip#6]
See:

`http://storage.googleapis.com/trademarks/application_images/2010/hr100101.zip`

**Comment by quietlyconfident** [comment]
````
Python 2.7.9 (default, Dec 10 2014, 23:46:04) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyremotezip import RemoteZip
>>> rz = RemoteZip('http://storage.googleapis.com/trademarks/application_images/2010/hr100101.zip')
>>> toc = rz.getTableOfContents()
>>> toc
[]
````

**Comment by fcvarela** [comment]
Fixed w/ latest PR

        from pyremotezip import RemoteZip
        rz = RemoteZip('http://storage.googleapis.com...
        toc = rz.getTableOfContents()
        toc
        [{'compressedsize': 0, 'filestart': 0, 'uncompressedsize': 0, 'filename': '779018/'}
